#!/usr/bin/env sh
# VW Import Script - Generated by secret migrate
# Review this script before running!

# Ensure we have a session
if [ -z "$BW_SESSION" ]; then
  echo "Error: BW_SESSION not set. Run: bw unlock"
  exit 1
fi

# Folders to organize secrets:
# - /

# Create secret items
echo 'eyJ0eXBlIjoxLCJuYW1lIjoiL1RFU1RfU0VDUkVUXzEyMyIsImxvZ2luIjp7InBhc3N3b3JkIjoibXktdGVzdC12YWx1ZS14eXoifSwibm90ZXMiOiJNaWdyYXRlZCBmcm9tOiAvdG1wL3Rlc3QtbWFuaWZlc3QuZW52In0=' | base64 -d | bw create item

echo "Import complete!"